### ISSUE TITLE
interpreter.shen fails

### ISSUE THREAD

**Issue by deech** [gregspurrier/shen-ruby#11]
Using Shen 15 and Ruby 2.0.0 the test in interpreter.shen fails  with the following message:
Qi interpreter - chapter 13: (tc +) = true
run time: 4.0531158447265625e-06 secs
passed
Qi interpreter - chapter 13: (load "interpreter.shen") = loaded
type#num : symbol
type#primitive_object : symbol
type#pattern : symbol
type#l_formula : symbol
l_interpreter : (A --> B)
read_eval_print_loop : (string --> A)
normal_form : (l_formula --> l_formula)

failed with error maximum stack depth exceeded

Qi interpreter - chapter 13: (tc -) = false
run time: 1.0013580322265625e-05 secs
passed
passed ... 111
failed ...1
pass rate ...99.10714285714286%

**Comment by gregspurrier** [comment]
I've updated the README with instructions on how to set the stack size for MRI 2.0.0+ and JRuby. See https://github.com/gregspurrier/shen-ruby#setting-stack-size.
