### ISSUE TITLE
Coerce Ruby Arrays to Vectors?

### ISSUE THREAD

**Issue by deech** [gregspurrier/shen-ruby#12]
This isn't an issue but a suggestion for the next version. How would you feel about coercing Ruby Arrays to vectors instead of cons lists? This way the length attribute can be preserved and to me it seems like a more intuitive mapping.

**Comment by gregspurrier** [comment]
With the new KLambda backend introduced in 0.11.0 and the Shen->Ruby interop introduced in 0.12.0, I decided to take the approach of requiring an explicit choice between lists and vectors when converting ruby Enumerables to Shen data types.

This gives better performance and doesn't constrain the user.
